services:
  sauer_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  sauer_backend:
    build:
      context: ./backend
    environment:
      DB_HOST: sauer_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 5050
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SESSION_SECRET: ${SESSION_SECRET:-Heslo}
    depends_on:
      sauer_db:
        condition: service_healthy
    restart: always

  sauer_frontend:
    build:
      context: ./Frontend
    depends_on:
      - sauer_backend
    restart: always

  sauer_db_backup:
    image: mysql:8.0
    profiles: ["tools"]
    volumes:
      - ./backend/database/backups:/backups
      - ./backend/database/script/backup.sh:/usr/local/bin/backup.sh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    entrypoint: ["/bin/bash", "/usr/local/bin/backup.sh"]
    depends_on:
      sauer_db:
        condition: service_healthy

  sauer_gateway:
    build:
      context: ./Caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - sauer_frontend
      - sauer_backend

  portainer:
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"
      - "8000:8000"

networks:
  default:
    name: portainer_network

volumes:
  db_data:
  caddy_data:
  caddy_config:
  portainer_data:
