services:
  db:
    image: mysql:8.0
    container_name: sauer_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: sauer_backend
    ports:
      - "5050:5050"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SESSION_SECRET: ${SESSION_SECRET:-Heslo}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db_backup:
    image: mysql:8.0
    container_name: sauer_db_backup
    volumes:
      - db_backups:/backups
      # Mapujeme náš nový skript do kontejneru
      - ./backend/database/script/backup.sh:/usr/local/bin/backup.sh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    entrypoint: ["/bin/bash", "/usr/local/bin/backup.sh"]
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./Frontend
    container_name: sauer_frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
  db_backups: